import React from 'react'

const About = () => {
  return (
    <div style={{marginTop:"100px",height:"100vh"}} >
      <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cum est nostrum optio, aliquam qui minus voluptatibus facilis ab? Eos quaerat sequi quis doloremque assumenda quae a unde eaque suscipit odit voluptatem iusto optio ipsum laboriosam, fugiat neque, earum architecto atque eius voluptatum. Nesciunt fugit doloremque laudantium autem vel culpa rem voluptas expedita sit odit delectus, aspernatur asperiores officiis neque earum exercitationem, facilis pariatur ipsum fugiat velit. Aspernatur, veniam et! Eligendi neque consequuntur quibusdam nihil rerum delectus nemo culpa eos tenetur vitae. Sit non recusandae neque odio fugit facilis, accusantium blanditiis sunt nostrum ratione minima at quae, commodi laborum iure nisi doloribus iusto corporis eaque officia tempora dolore numquam vel sapiente. Veniam, quaerat corrupti sint, quas ab commodi sequi provident aliquid, error unde incidunt accusantium iste consequatur doloribus eveniet recusandae corporis esse odio. Alias vel eveniet quas esse sunt. Perspiciatis harum eligendi similique sit provident sint odit atque accusantium qui pariatur blanditiis vero, cum possimus minus aut voluptas. Consectetur aspernatur, est veniam provident, deserunt molestiae dignissimos repellendus architecto illum aperiam, qui vero. Error corrupti beatae laborum officia esse quas impedit nulla, blanditiis voluptate delectus? Placeat porro modi eos? Impedit, in? Voluptas animi nobis dolore nesciunt, debitis molestias ratione nostrum impedit dolorem suscipit quia commodi facilis eius hic. Necessitatibus explicabo dolorum culpa vitae voluptas voluptate saepe, dolor, animi provident quo voluptatum perferendis illo possimus. Suscipit, voluptatum vero? Facere dolore excepturi saepe culpa enim odio! Adipisci natus vero at illo architecto beatae, similique rerum ullam repellendus odio quidem atque porro vel delectus ducimus rem sunt eos quo fuga temporibus? Quasi molestias repellat iusto, nam minus optio doloribus omnis atque dolores enim nemo facilis, eos illum, ut laboriosam quibusdam aut placeat? Sed animi cum ex sequi vel quam, veniam est! Odio ipsum reprehenderit officia ab optio voluptatem voluptates, dolore fugit nam hic cupiditate consequuntur! </h1>
    </div>
  )
}

export default About
